version: "3"

services:
  web:
    build: .
    ports:
      - "21626:3000"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - NODE_ENV=${NODE_ENV}
      - API_PORT=${API_PORT}
      - FRONTEND_URL=${FRONTEND_URL}
